"""rename department

Revision ID: f6da2d79338e
Revises: c467c23ba9b0
Create Date: 2024-06-26 19:31:22.591748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6da2d79338e'
down_revision = 'c467c23ba9b0'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
